[tool.poetry]
name = "birb"
version = "0.1.0"
description = "Code for the BIRB benchmark."
authors = ["Anonymous"]
license = "Apache 2.0"

[tool.poetry.dependencies]
python = ">=3.10,<3.11"
absl-py = "^1.3.0"
apache-beam = {version = "^2.46.0", extras = ["gcp"]}
clu = "^0.0.8"
flax = "^0.6.7"
jax = "^0.4.1"
ml-collections = "^0.1.1"
optax = "^0.1.4"
# Note that tensorflow and tensorflow-io versions must be synchronized.
# See: https://github.com/tensorflow/io#tensorflow-version-compatibility
tensorflow = "=2.11.0"
tensorflow-io = "=0.31"
tensorflow-datasets = {version = "^4.8.0", extras = ["dev"]}
pandas = "1.5.1"
etils = {version = "^0.9.0", extras = ["epath"]}

[tool.poetry.group.dev.dependencies]
librosa = "^0.9.2"
numpy = "^1.22.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
